### ISSUE TITLE
Extraer la información sobre tropos principales de películas de TvTropes

### ISSUE THREAD

**Issue by jlgallego99** [jlgallego99/TropesToGo#10]
Extraer la información de tropos de películas que hay en TvTropes (HUs #6 y #7). La información de los tropos debe estar siempre actualizada como se especifica en la HU #9 por lo que se deben tener en cuenta la diferencia entre cómo están organizados los contenidos entre páginas. Todo esto debe estar bien documentado para satisfacer #1.

**Comment by JJ** [comment]
Recuerda que todos los issues son problemas; no pongas la solución (analizar y esquematizar) antes del problema (extraer la información), porque puedes acabar haciendo mucho más que lo que necesitas). En este caso, puede que no tengas que analizar la estructura de *toda* la web, sino sólo la parte que realmente te interese; y dentro de esta, puede que sólo tengas que extraer cierta información.

**Comment by jlgallego99** [comment]
Reformulado para expresar solo el problema que se quiere resolver con este issue
