### ISSUE TITLE
Generalizar y simplificar scraping con recursos reales y en tests

### ISSUE THREAD

**Issue by jlgallego99** [jlgallego99/TropesToGo#101]
Ahora mismo existen dos funciones de scraping, una con readers y otra con paginas, que dificultan bastante utilizar el API y entenderlo, teniendo demasiados parámetros. Tanto los usuarios como el tribunal #1 deben entender bien lo desarrollado y se debe seguir siempre la solucion mas simple y efectiva posible

Por eso, y debido a que los objetos Page ya contienen el documento Goquery con el que hacer el scraper, se debe unificar todo en la misma función para testearla mejor y que sea más sencilla, tanto en el uso como en eficiencia #45. En los tests se utilizará la misma función de scraping que en los casos reales que se usen peticiones HTTP, que trabaja con los objetos Pagina, siguiendo un modelado unificado.

Por tanto, el test debe encargarse de construir todos los objetos Pagina de TvTropes #6 ya con un documento Goquery cuyos contenidos han sido leidos de ficheros locales, para utilizar siempre en tests recursos propios y no depender de la red

**Comment by JJ** [comment]
Incluso con la implementación tan avanzada, no debes de perder de vista las historias de usuario. Si se hace una refactorización, es para añadir valor al cliente. Si no, no estás haciendo nada.
