### ISSUE TITLE
La descripción de los milestones (al menos los iniciales) deben ser parte también parte del milestone inicial

### ISSUE THREAD

**Issue by JJ** [jlgallego99/TropesToGo#18]
Implícitamente, se entiende que [este milestone](https://github.com/jlgallego99/TropesToGo/milestone/1) al hablar de "planificación", incluye los milestones, pero es conveniente siempre que los productos mínimamente viables se incluyan explícitamente.
También conviene recordar que se trata de productos *mínimamente* viables, así que los milestones iniciales son suficientes.

**Comment by jlgallego99** [comment]
Quiere decir que dentro de la propia descripción del milestone 0 deben ir incluidos el resto de milestones con su descripción?
