### ISSUE TITLE
Representar el código inicial siguiendo el modelo del problema

### ISSUE THREAD

**Issue by jlgallego99** [jlgallego99/TropesToGo#44]
El código debe estar organizado desde el principio siguiendo el modelado que se ha especificado para el problema #39. Deben estar definidas las estructuras de datos, interfaces, posibles errores o excepciones, etc. que se usen en el dominio del problema para dar inicio a la implementación del software #6 #7 #30

**Comment by JJ** [comment]
Es una tarea, no un problema. De aquí no está nada claro como llegas a un interfaz "get, getall, add, update".
