### ISSUE TITLE
Representar la información de obras y tropos de TvTropes

### ISSUE THREAD

**Issue by jlgallego99** [jlgallego99/TropesToGo#52]
Para #44 y siguiendo el modelo del problema #39 se tiene que representar la información relevante para el usuario de todas las obras con sus tropos que hay en TvTropes, para cualquier tipo de medio audiovisual #6. Esta información se obtendrá en el futuro de las páginas recolectadas #51 y será la que finalmente utilice el investigador #46, por lo que debe poder representarse en distintos formatos #30
Una obra contendrá una serie de tropos y debe tener información adicional de metadatos que permitan diferenciarla de otras con el mismo nombre #8 y saber lo actualizados que están #9

**Comment by JJ** [comment]
No está claro aquí que te pida clasificar los tropos en 4 tipos diferentes, y que sean esos tipos.

**Comment by JJ** [comment]
De hecho, también un tropo puede pertenecer a diferentes grupos. Puede ser un tropo de título, pero también un "twisted trope", y uno de humor.

**Comment by jlgallego99** [comment]
Abro el issue #58 para abordar el tema de los grupos de tropos en un futuro milestone, ya que como hablamos ayer tendrá sentido que conforme un milestone por sí mismo
