### ISSUE TITLE
Sería conveniente que en issues y PRs diferenciaras las HUs con las que estás tratando

### ISSUE THREAD

**Issue by JJ** [jlgallego99/TropesToGo#56]
Cuando te encuentras con issues como este #52 con un montón de enlaces, es difícil saber cuál es la HU, y de hecho si realmente se está trabajando con una HU.

No existe ninguna convención para hacer estas cosas; en el PR sí se ve claro porque incluye el título completo del issue (que incluye HU), pero una forma que se me ocurre es crear "labels" por HU y asignar esos labels al issue para que claramente se vea con qué HUs se están tratando. Se pueden usar todas las etiquetas que se quiera, porque un issue o PR puede usar todas las HUs que sea necesario (en general, siempre habrá una HU y la del tribunal)

**Comment by jlgallego99** [comment]
Me parece bien la idea de las etiquetas, crearé una etiqueta por cada HU y las añadiré a los issues que cree
